import Head from 'next/head'
import Header from '../components/Header'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pexels</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>
      <Main/>
    </div>
  )
}
